"""
Django settings for power_outage_notify project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2$k5oiw00n1fb@rs=_&@=7#-5ugnt!ykg&+zmlld+02@3ctu$m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*", ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'notify.apps.NotifyConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'power_outage_notify.urls'

TEMPLATES = [
    {
        'BACKEND':  'django.template.backends.django.DjangoTemplates',
        'DIRS':     [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS':  {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'power_outage_notify.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME':   os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Email Setting
# 发送邮件设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# SMTP地址
EMAIL_HOST = 'smtp.126.com'
# SMTP端口
EMAIL_PORT = 25
# TODO: 请设置自己用于发邮件的邮箱, 设置自己的邮箱及授权码
# 自己的邮箱
EMAIL_HOST_USER = 'xxx@126.com'
# 自己的邮箱授权码，非密码
EMAIL_HOST_PASSWORD = 'xxxx'


EMAIL_SUBJECT_PREFIX = '[Power Outage Notify]'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# 与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false
EMAIL_USE_TLS = False

# logging configurations
log_save_path = {
    'server': 'log/server/service.log',
}

for log_path in log_save_path.values():
    log_dir = os.path.dirname(log_path)
    if not os.path.isdir(log_dir):
        os.makedirs(log_dir)

LOG_FILE_BACKUP_DAYS = 5

LOGGING = {
    'version':                  1,
    'disable_existing_loggers': False,
    'formatters':               {
        'default':       {
            'format': '[%(asctime)s] %(levelname)s [%(funcName)s: %(filename)s, %(lineno)d] %(message)s'
        },
        'thread_simple': {
            'format': '[%(asctime)s] %(levelname)s [thread: %(threadName)s] %(message)s'
        },
        'thread':        {
            'format': '[%(asctime)s] %(levelname)s [thread: %(threadName)s] [%(funcName)s: %(filename)s, %(lineno)d] %(message)s'
        },
    },
    'handlers':                 {
        'console':     {
            'level':     'INFO',
            'class':     'logging.StreamHandler',
            'formatter': 'default',
        },
        'file_backup': {
            'level':       'INFO',
            'class':       'logging.handlers.RotatingFileHandler',
            'filename':    log_save_path['server'],
            'formatter':   'default',
            'maxBytes':    1024 * 1024,  # 1M
            'backupCount': LOG_FILE_BACKUP_DAYS,
        },
        'file':        {
            'level':       'INFO',
            'class':       'logging.handlers.TimedRotatingFileHandler',
            'filename':    log_save_path['server'],
            'formatter':   'default',
            'when':        'midnight',
            'interval':    1,
            'backupCount': LOG_FILE_BACKUP_DAYS,
        },
    },
    'loggers':                  {
        '':        {
            'handlers':  ['file'],
            'level':     'DEBUG',
            'propagate': True,
        },
        'file':    {
            'handlers':  ['file'],
            'level':     'DEBUG',
            'propagate': True,
        },
        'console': {
            'handlers':  ['console'],
            'level':     'DEBUG',
            'propagate': True,
        },
    }
}

# ==== 定时任务 ====
# 每天 19:30 分爬取一次通告信息
CRONJOBS = (
    ('30 19 * * *', 'notify.task.task_crawl_power_outage_info'),
)
